version: '3.8'

services:
  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    ports:
      - "8080:8080"
    environment:
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=adminpassword
      - WORDPRESS_EMAIL=admin@example.com
      - WORDPRESS_SITE_NAME=My WordPress Site
      - MARIADB_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - wordpress_data:/bitnami/wordpress
    networks:
      - wordpress_network

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=wordpresspassword
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - wordpress_network

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge