version: '3.3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=onetenplus
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - ~/my_docker/docker_volume/mariadb:/bitnami
  wordpress:
    image: 'bitnami/wordpress:latest'
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    environment:
      - WORDPRESS_USERNAME=onetenplus
      - WORDPRESS_PASSWORD=codehamster
      - WORDPRESS_DATABASE_USER=onetenplus
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ~/my_docker/docker_volume/wordpress:/bitnami
  phpmyadmin:
    image: 'bitnami/phpmyadmin:latest'
    depends_on:
      - mariadb
    ports:
      - '8080:80'
      - '4843:443'
    volumes:
      - ~/my_docker/docker_volume/phpmyadmin:/bitnami
