version: '3.8'

services:
  db:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: onetenplus
      MARIADB_PASSWORD: beariot1234
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./wordpress_mariadb_data:/bitnami/mariadb
    networks:
      - wordpress_network

  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DATABASE_HOST: db:3306
      WORDPRESS_DATABASE_USER: onetenplus
      WORDPRESS_DATABASE_PASSWORD: beariot1234
      WORDPRESS_DATABASE_NAME: wordpress_db
    ports:
      - "8080:80"
    volumes:
      - ./wordpress_wordpress_data:/bitnami/wordpress
    depends_on:
      - db
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
