version: '1'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=example_root_password
      - MARIADB_DATABASE=wordpress_db
      - MARIADB_USER=wordpress_user
      - MARIADB_PASSWORD=example_password
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - wordpress_network

  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_NAME=wordpress_db
      - WORDPRESS_DATABASE_USER=wordpress_user
      - WORDPRESS_DATABASE_PASSWORD=example_password
      - WORDPRESS_USERNAME=admin 
      - WORDPRESS_PASSWORD=1234
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    networks:
      - wordpress_network

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge